---
- name: Add php 5.6 repo
  apt_repository: repo='ppa:ondrej/php5-5.6'
- name: Update apt-cache
  apt: update_cache=yes
- name: Install php5-fpm
  apt: name='php5-fpm' state=latest
- name: Install php5-curl
  apt: name='php5-curl' state=latest
- name: Install php5-gd
  apt: name='php5-gd' state=latest
- name: Install php5-mcrypt
  apt: name='php5-mcrypt'
- name: Install php5-mysql
  apt: name='php5-mysql'
