---
- name: Create public_html folder
  file: path=/srv/www/{{ server_hostname }}/public_html state=directory group=www-data owner=www-data recurse=yes
- name: Create logs folder
  file: path=/srv/www/{{ server_hostname }}/logs state=directory group=www-data owner=www-data recurse=yes
- name: Create logs files
  file: path=/srv/www/{{ server_hostname }}/logs/{{ item }}.log state=touch group=www-data owner=www-data
  with_items:
    - error
    - access
- name: Copy nginx configuration for wordpress
  template: src=php-fpm-enable.conf dest=/etc/nginx/sites-available/{{ server_hostname }}
- name: Create symlink to {{ server_hostname }}
  file: src=/etc/nginx/sites-available/{{ server_hostname }} dest=/etc/nginx/sites-enabled/{{ server_hostname }} state=link
  notify: restart nginx
